// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEcrqCxKAqY2Y-2_BcEHLcuBo7W4MXsu8',
    appId: '1:318926983434:web:25b4711c5c48902aa52af3',
    messagingSenderId: '318926983434',
    projectId: 'book-me-project',
    authDomain: 'book-me-project.firebaseapp.com',
    storageBucket: 'book-me-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbhv0AjCgFiTFz-b-WTYWmDK4iGRnxaw',
    appId: '1:318926983434:android:d5aac545b21a2f83a52af3',
    messagingSenderId: '318926983434',
    projectId: 'book-me-project',
    storageBucket: 'book-me-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcu3x4ALJn9A3a1M5W5QRrvp0RYbWI8EA',
    appId: '1:318926983434:ios:0b80c49fa8b4b917a52af3',
    messagingSenderId: '318926983434',
    projectId: 'book-me-project',
    storageBucket: 'book-me-project.appspot.com',
    iosClientId: '318926983434-uq4gg7m3n17c24o1gk94lma8m83122p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcu3x4ALJn9A3a1M5W5QRrvp0RYbWI8EA',
    appId: '1:318926983434:ios:0b80c49fa8b4b917a52af3',
    messagingSenderId: '318926983434',
    projectId: 'book-me-project',
    storageBucket: 'book-me-project.appspot.com',
    iosClientId: '318926983434-uq4gg7m3n17c24o1gk94lma8m83122p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );
}
